package com.example.demo.mapper.generator;

import com.example.demo.model.generator.PurchaseHistory;
import com.example.demo.model.generator.PurchaseHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PurchaseHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_history
     *
     * @mbg.generated
     */
    long countByExample(PurchaseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_history
     *
     * @mbg.generated
     */
    int deleteByExample(PurchaseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_history
     *
     * @mbg.generated
     */
    int insert(PurchaseHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_history
     *
     * @mbg.generated
     */
    int insertSelective(PurchaseHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_history
     *
     * @mbg.generated
     */
    List<PurchaseHistory> selectByExample(PurchaseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_history
     *
     * @mbg.generated
     */
    PurchaseHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PurchaseHistory record, @Param("example") PurchaseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PurchaseHistory record, @Param("example") PurchaseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PurchaseHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PurchaseHistory record);
}