spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch_sample_db?useSSL=false&requireSSL=false
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations:
    - /mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
