package com.example.demo.model.generator;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class ExecutionHistoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table execution_history
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table execution_history
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table execution_history
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_history
     *
     * @mbg.generated
     */
    public ExecutionHistoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_history
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_history
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_history
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_history
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_history
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_history
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_history
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_history
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_history
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_history
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table execution_history
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> successfulTerminationExecutedAtCriteria;

        protected List<Criterion> allCriteria;

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
            successfulTerminationExecutedAtCriteria = new ArrayList<Criterion>();
        }

        public List<Criterion> getSuccessfulTerminationExecutedAtCriteria() {
            return successfulTerminationExecutedAtCriteria;
        }

        protected void addSuccessfulTerminationExecutedAtCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            successfulTerminationExecutedAtCriteria.add(new Criterion(condition, value, "org.apache.ibatis.type.LocalDateTimeTypeHandler"));
            allCriteria = null;
        }

        protected void addSuccessfulTerminationExecutedAtCriterion(String condition, LocalDateTime value1, LocalDateTime value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            successfulTerminationExecutedAtCriteria.add(new Criterion(condition, value1, value2, "org.apache.ibatis.type.LocalDateTimeTypeHandler"));
            allCriteria = null;
        }

        public boolean isValid() {
            return criteria.size() > 0
                || successfulTerminationExecutedAtCriteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            if (allCriteria == null) {
                allCriteria = new ArrayList<Criterion>();
                allCriteria.addAll(criteria);
                allCriteria.addAll(successfulTerminationExecutedAtCriteria);
            }
            return allCriteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
            allCriteria = null;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSuccessfulTerminationExecutedAtIsNull() {
            addCriterion("successful_termination_executed_at is null");
            return (Criteria) this;
        }

        public Criteria andSuccessfulTerminationExecutedAtIsNotNull() {
            addCriterion("successful_termination_executed_at is not null");
            return (Criteria) this;
        }

        public Criteria andSuccessfulTerminationExecutedAtEqualTo(LocalDateTime value) {
            addSuccessfulTerminationExecutedAtCriterion("successful_termination_executed_at =", value, "successfulTerminationExecutedAt");
            return (Criteria) this;
        }

        public Criteria andSuccessfulTerminationExecutedAtNotEqualTo(LocalDateTime value) {
            addSuccessfulTerminationExecutedAtCriterion("successful_termination_executed_at <>", value, "successfulTerminationExecutedAt");
            return (Criteria) this;
        }

        public Criteria andSuccessfulTerminationExecutedAtGreaterThan(LocalDateTime value) {
            addSuccessfulTerminationExecutedAtCriterion("successful_termination_executed_at >", value, "successfulTerminationExecutedAt");
            return (Criteria) this;
        }

        public Criteria andSuccessfulTerminationExecutedAtGreaterThanOrEqualTo(LocalDateTime value) {
            addSuccessfulTerminationExecutedAtCriterion("successful_termination_executed_at >=", value, "successfulTerminationExecutedAt");
            return (Criteria) this;
        }

        public Criteria andSuccessfulTerminationExecutedAtLessThan(LocalDateTime value) {
            addSuccessfulTerminationExecutedAtCriterion("successful_termination_executed_at <", value, "successfulTerminationExecutedAt");
            return (Criteria) this;
        }

        public Criteria andSuccessfulTerminationExecutedAtLessThanOrEqualTo(LocalDateTime value) {
            addSuccessfulTerminationExecutedAtCriterion("successful_termination_executed_at <=", value, "successfulTerminationExecutedAt");
            return (Criteria) this;
        }

        public Criteria andSuccessfulTerminationExecutedAtIn(List<LocalDateTime> values) {
            addSuccessfulTerminationExecutedAtCriterion("successful_termination_executed_at in", values, "successfulTerminationExecutedAt");
            return (Criteria) this;
        }

        public Criteria andSuccessfulTerminationExecutedAtNotIn(List<LocalDateTime> values) {
            addSuccessfulTerminationExecutedAtCriterion("successful_termination_executed_at not in", values, "successfulTerminationExecutedAt");
            return (Criteria) this;
        }

        public Criteria andSuccessfulTerminationExecutedAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addSuccessfulTerminationExecutedAtCriterion("successful_termination_executed_at between", value1, value2, "successfulTerminationExecutedAt");
            return (Criteria) this;
        }

        public Criteria andSuccessfulTerminationExecutedAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addSuccessfulTerminationExecutedAtCriterion("successful_termination_executed_at not between", value1, value2, "successfulTerminationExecutedAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table execution_history
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table execution_history
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}